services:
    php:
        container_name: busca-app-php
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/html/laravel-app
        volumes:
            - ./laravel-app:/var/www/html/laravel-app
        networks:
            - busca_app_network

    nginx:
        container_name: busca-app-nginx
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./laravel-app:/var/www/html/laravel-app
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - busca_app_network

    mysql:
        container_name: busca-app-mysql
        image: mysql:8.0
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: busca-app
            MYSQL_USER: busca-app
            MYSQL_PASSWORD: busca-app
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - dbdata:/var/lib/mysql
            - ./docker/mysql/init-scripts:/docker-entrypoint-initdb.d
        networks:
            - busca_app_network

volumes:
    dbdata:
        driver: local

networks:
    busca_app_network:
        driver: bridge